In [10]:
#项目7-例7-2代码
#数据准备
from sklearn.datasets import load_breast_cancer #导入肺癌数据集
from sklearn.svm import SVC     #导入支持向量机分类模块
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler

x,y=load_breast_cancer().data,load_breast_cancer().target 
x=StandardScaler().fit_transform(x)#数据标准化处理
# x.shape,x.shape[0]
x,y

(array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
          2.75062224,  1.93701461],
        [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
         -0.24388967,  0.28118999],
        [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
          1.152255  ,  0.20139121],
        ...,
        [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
         -1.10454895, -0.31840916],
        [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
          1.91908301,  2.21963528],
        [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
         -0.04813821, -0.75120669]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
   

In [9]:
#使用网格搜索法确定最优的参数值
from sklearn.model_selection import StratifiedShuffleSplit  #分层抽样
from sklearn.model_selection import GridSearchCV            #网格搜索

gamma_range=np.logspace(-10,1,20) # 等比
coef0_range=np.linspace(0,5,10) # 等差

param_grid=dict(gamma=gamma_range,coef0=coef0_range)
cv=StratifiedShuffleSplit(n_splits=5,test_size=0.3,random_state=420)  #对样本进行分层抽样,5次划分
grid=GridSearchCV(SVC(kernel="poly",degree=1),param_grid=param_grid,cv=cv) #使用网格搜索法寻找参数的最优值
grid.fit(x,y)
print("最优参数值为：%s"%grid.best_params_)
print("最优参数值为：%s"%grid.best_params_['coef0'])
print("最优参数值为：%s"%grid.best_params_['gamma'])

print("选取该参数值时，模型的预测准确率为：%f"%grid.best_score_)

{'gamma': array([1.00000000e-10, 3.79269019e-10, 1.43844989e-09, 5.45559478e-09,
       2.06913808e-08, 7.84759970e-08, 2.97635144e-07, 1.12883789e-06,
       4.28133240e-06, 1.62377674e-05, 6.15848211e-05, 2.33572147e-04,
       8.85866790e-04, 3.35981829e-03, 1.27427499e-02, 4.83293024e-02,
       1.83298071e-01, 6.95192796e-01, 2.63665090e+00, 1.00000000e+01]), 'coef0': array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])}
{'gamma': array([1.00000000e-10, 3.79269019e-10, 1.43844989e-09, 5.45559478e-09,
       2.06913808e-08, 7.84759970e-08, 2.97635144e-07, 1.12883789e-06,
       4.28133240e-06, 1.62377674e-05, 6.15848211e-05, 2.33572147e-04,
       8.85866790e-04, 3.35981829e-03, 1.27427499e-02, 4.83293024e-02,
       1.83298071e-01, 6.95192796e-01, 2.63665090e+00, 1.00000000e+01]), 'coef0': array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.

In [3]:
gamma_range=np.logspace(-10,1,20)
coef0_range=np.linspace(0,5,10)
print(type(gamma_range))
print(coef0_range)
a=[1,2,'3']
param_grid=dict(gamma=gamma_range,coef10=coef0_range,ta=a)
print(type(param_grid))
print(param_grid['gamma'],'\n',param_grid['coef10'],'\n',param_grid['ta'])

<class 'numpy.ndarray'>
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
<class 'dict'>
[1.00000000e-10 3.79269019e-10 1.43844989e-09 5.45559478e-09
 2.06913808e-08 7.84759970e-08 2.97635144e-07 1.12883789e-06
 4.28133240e-06 1.62377674e-05 6.15848211e-05 2.33572147e-04
 8.85866790e-04 3.35981829e-03 1.27427499e-02 4.83293024e-02
 1.83298071e-01 6.95192796e-01 2.63665090e+00 1.00000000e+01] 
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ] 
 [1, 2, '3']


In [4]:
from sklearn.model_selection import StratifiedShuffleSplit
import numpy as np
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],
              [1, 2],[3, 4], [1, 2], [3, 4]])#训练数据集8*2
y = np.array([0, 0, 1, 1,0,0,1,1])#类别数据集8*1

ss=StratifiedShuffleSplit(n_splits=2,train_size=0.75,test_size=0.25,random_state=0)#分成5组，测试比例为0.25，训练比例是0.75
tt,sss=ss.split(X,y)
print(ss.split(X,y))
print(tt,sss)
for train_index, test_index in ss.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)#获得索引值
   X_train, X_test = X[train_index], X[test_index]#训练集对应的值
   y_train, y_test = y[train_index], y[test_index]#类别集对应的值


<generator object BaseShuffleSplit.split at 0x00000205B7CCB220>
(array([5, 2, 6, 4, 1, 3], dtype=int64), array([7, 0], dtype=int64)) (array([4, 3, 5, 2, 7, 1], dtype=int64), array([6, 0], dtype=int64))
TRAIN: [5 2 6 4 1 3] TEST: [7 0]
TRAIN: [4 3 5 2 7 1] TEST: [6 0]
